---
title: "Making (Nice!) Plots in R"
subtitle: "An R exercise within the Umbrella Academy course"
description: "This is an exercise to help 'wet lab' scientists feel comfortable manipulating data and creating common charts in R"

author:
  - name: Kelsey Monson
    degrees:
      - PhD
      - MS
    orcid: 0000-0003-1093-8628
    email: kelsey.monson@mssm.edu
    affiliations:
      - ref: ISMMS

affiliations:
  - id: ISMMS
    name: Icahn School of Medicine at Mount Sinai
    city: New York
    state: NY
    department: Immunology and Immunotherapy

title-block-banner: "#f0f3f5"
title-block-banner-color: "black"

keywords: "R, Data Analysis, Data Viz"
date: today

format: 
  html: 
    toc: true
    number-sections: true
    css: style.css
    
fig-cap-location: margin
editor: visual
---

## Introduction

The goal of **The Umbrella Academy** class is to familiarize "wet lab" scientists with useful "dry lab" tools they may want to use. Therefore, this exercise is geared primarily towards basic data manipulation to generate aesthetically pleasing plots in R.

R is an excellent tool for generating beautiful data visualizations, and is much more flexible and customizable than other tools like Excel or GraphPad.

First, let's familiarize ourselves with some basics of working with R in RStudio.

### R and RStudio

By now, you should have installed what's often called "base R." According to its creators, R is "an integrated suite of software facilities for data manipulation, calculation and graphical display" (you can read more about it [here](https://www.r-project.org/about.html)).

```{r}
getwd()
```
